
<html><head>
<title>flibs/m_exception - flibs</title>
<style type="text/css"><!--
    HTML {
	background: 	#FFFFFF;
	color: 		black;
    }
    BODY {
	background: 	#FFFFFF;
	color:	 	black;
    }
    DIV.doctools {
	margin-left:	10%;
	margin-right:	10%;
    }
    DIV.doctools H1,DIV.doctools H2 {
	margin-left:	-5%;
    }
    H1, H2, H3, H4 {
	margin-top: 	1em;
	font-family:	sans-serif;
	font-size:	large;
	color:		#005A9C;
	background: 	transparent;
	text-align:		left;
    }
    H1.title {
	text-align: center;
    }
    UL,OL {
	margin-right: 0em;
	margin-top: 3pt;
	margin-bottom: 3pt;
    }
    UL LI {
	list-style: disc;
    }
    OL LI {
	list-style: decimal;
    }
    DT {
	padding-top: 	1ex;
    }
    UL.toc,UL.toc UL, UL.toc UL UL {
	font:		normal 12pt/14pt sans-serif;
	list-style:	none;
    }
    LI.section, LI.subsection {
	list-style: 	none;
	margin-left: 	0em;
	text-indent:	0em;
	padding: 	0em;
    }
    PRE {
	display: 	block;
	font-family:	monospace;
	white-space:	pre;
	margin:		0%;
	padding-top:	0.5ex;
	padding-bottom:	0.5ex;
	padding-left:	1ex;
	padding-right:	1ex;
	width:		100%;
    }
    PRE.example {
	color: 		black;
	background: 	#f5dcb3;
	border:		1px solid black;
    }
    UL.requirements LI, UL.syntax LI {
	list-style: 	none;
	margin-left: 	0em;
	text-indent:	0em;
	padding:	0em;
    }
    DIV.synopsis {
	color: 		black;
	background: 	#80ffff;
	border:		1px solid black;
	font-family:	serif;
	margin-top: 	1em;
	margin-bottom: 	1em;
    }
    UL.syntax {
	margin-top: 	1em;
	border-top:	1px solid black;
    }
    UL.requirements {
	margin-bottom: 	1em;
	border-bottom:	1px solid black;
    }
--></style>
</head>
<! -- Generated from file 'reporting/m_exception.man' by tcllib/doctools with format 'html'
   -->
<! -- Copyright &copy; 2008 Michael Baudin michael.baudin@gmail.com   -- Copyright &copy; 2008 Arjen Markus arjenmarkus@sourceforge.net
   -->
<! -- CVS: $Id: m_exception.html,v 1.3 2013/05/13 08:03:19 knystrom Exp $ flibs/m_exception.n
   -->
<body><div class="doctools">
<h1 class="title">flibs/m_exception(n) 1.0  &quot;flibs&quot;</h1>
<div id="name" class="section"><h2><a name="name">Name</a></h2>
<p>flibs/m_exception - Manage exceptions</p>
</div>
<div id="toc" class="section"><h2><a name="toc">Table Of Contents</a></h2>
<ul class="toc">
<li class="section"><a href="#toc">Table Of Contents</a></li>
<li class="section"><a href="#synopsis">Synopsis</a></li>
<li class="section"><a href="#section1">Description</a></li>
<li class="section"><a href="#section2">OVERVIEW</a>
<ul>
<li class="subsection"><a href="#subsection1">Simple use-case</a></li>
<li class="subsection"><a href="#subsection2">Controlling the execution</a></li>
<li class="subsection"><a href="#subsection3">Controlling output</a></li>
<li class="subsection"><a href="#subsection4">Pseudo-catch</a></li>
</ul>
</li>
<li class="section"><a href="#section3">ROUTINES</a></li>
<li class="section"><a href="#section4">TODO</a></li>
<li class="section"><a href="#copyright">Copyright</a></li>
</ul>
</div>
<div id="synopsis" class="section"><h2><a name="synopsis">Synopsis</a></h2>
<div class="synopsis">
<ul class="syntax">
<li><a href="#1"><b class="method">exception_raiseFatalError</b> ( <i class="arg">message</i> )</a></li>
<li><a href="#2"><b class="method">exception_raiseError</b> ( <i class="arg">message</i> )</a></li>
<li><a href="#3"><b class="method">exception_raiseWarning</b> ( <i class="arg">message</i> )</a></li>
<li><a href="#4"><b class="method">exception_raiseInformation</b> ( <i class="arg">message</i> )</a></li>
<li><a href="#5"><b class="method">exception_raiseFailure</b> ( <i class="arg">message</i> )</a></li>
<li><a href="#6"><b class="method">exception_setstoponerror</b> ( <i class="arg">stoponerror</i> )</a></li>
<li><a href="#7"><b class="method">exception_initcounter</b> ( )</a></li>
<li><a href="#8"><b class="method">exception_getcounter</b> ( )</a></li>
<li><a href="#9"><b class="method">exception_report</b> ( )</a></li>
<li><a href="#10"><b class="method">exception_setlogunit</b> ( <i class="arg">unitnumber</i> )</a></li>
<li><a href="#11"><b class="method">exception_getlogunit</b> ( ) result ( logunit )</a></li>
<li><a href="#12"><b class="method">exception_logactive</b> ( <i class="arg">bool</i> )</a></li>
<li><a href="#13"><b class="method">exception_islogactive</b> ( ) result ( islogactive )</a></li>
<li><a href="#14"><b class="method">exception_catch</b> ( <i class="arg">callback</i> <i class="arg">, status</i> ) result ( islogactive )</a></li>
</ul>
</div>
</div>
<div id="section1" class="section"><h2><a name="section1">Description</a></h2>
<p>Provides services to generate different levels of exceptions
and display the message of the exception.
Five levels of exceptions can be generated, from the lowest
to the highest level :</p>
<ul class="itemized">
<li><p>information, warning : just print a message and continue</p></li>
<li><p>error, fatal_error and failure : prints a message and stop the execution</p></li>
</ul>
</div>
<div id="section2" class="section"><h2><a name="section2">OVERVIEW</a></h2>
<div id="subsection1" class="subsection"><h3><a name="subsection1">Simple use-case</a></h3>
<p>Suppose that one would like to compute the square root of one
real value. The &quot;compute_sqrt&quot; function takes one positive real argument,
and if the argument is negative, one cannot compute the square root so
that one would generate an error. In the following example, extracted from the
unit tests included in the project, one uses the static method &quot;exception_raiseError&quot;
to display a user-friendly message and stop the execution of the program</p>
<pre class="example">
    function compute_sqrt ( value ) result ( root )
      use m_exception
      implicit none
      real, intent(in) :: value
      real :: root
      if ( value &lt; 0. ) then
        call exception_raiseError ( &quot;Value is negative in compute_sqrt&quot; )
      else 
        root = sqrt ( value )
      endif
   end function compute_sqrt
   real :: root
   root = compute_sqrt ( -1. )
</pre>
<p>In the previous example, the standard output is written so that the
 following message appears on screen.</p>
<pre class="example">
   Error.
   Message: Value is negative in compute_sqrt
</pre>
</div>
<div id="subsection2" class="subsection"><h3><a name="subsection2">Controlling the execution</a></h3>
<p>The client code can control the behaviour of the component each time
 an exception is raised.
 The default behaviour is to stop the execution. This can be modified
 by calling &quot;exception_setstoponerror&quot; in order to continue the execution,
 even if error, fatal error or failure exceptions are raised.</p>
<p>In the following example, the static method &quot;exception_setstoponerror&quot; is 
   called so that an error does not interrupt the execution.</p>
<pre class="example">
   call exception_setstoponerror ( .false. )
   call exception_raiseError ( &quot;There is an error, but the execution will continue.&quot; )
</pre>
</div>
<div id="subsection3" class="subsection"><h3><a name="subsection3">Controlling output</a></h3>
<p>The default behaviour is to write messages onto the standard output
   each time an exception is raised.
   This can be modified in two ways.</p>
<ul class="itemized">
<li><p>the first possibility is to disable the writing of the messages 
     with &quot;exception_logactive&quot;. This feature might be useful in the case
     where a component has known bugs but generates lots of unwanted
     exceptions messages.</p></li>
<li><p>the second possibility is to connect the component to an existing unit
     with &quot;exception_setlogunit&quot;, so that the messages are written
     on the given logical unit number. 
     This allows for example to write on an existing log file, may be the log 
     file manage by the m_logger component included in the project.</p></li>
</ul>
<p>In the following example, the client code first disables all output,
   set &quot;stoponerror&quot; to false and generates an error which is not displayed
   and does not interrupt the execution.</p>
<pre class="example">
   call exception_setstoponerror ( .false. )
   call exception_logactive ( .false. )
   call exception_raiseError ( &quot;This message will not be displayed and the execution will continue.&quot; )
   call exception_logactive ( .true. )
   call exception_raiseError ( &quot;This message WILL be displayed and the execution will continue.&quot; )
</pre>
<p>In the following example, the client code connect the m_exception component to 
   an existing unit so that the exception messages are written onto a client log file.</p>
<pre class="example">
     log_fileunit = 12
     call exception_setstoponerror ( .false. )
     open ( log_fileunit , FILE= &quot;log_file.log&quot; )
     call exception_setlogunit ( log_fileunit )
     call exception_raiseError ( &quot;This message will be written in log_file.log and the execution will continue.&quot; )
     call exception_setlogunit ( 0 )
     call exception_raiseError ( &quot;This message will be written on standard output and the execution will continue.&quot; )
     close ( log_fileunit )
</pre>
<p>In the following example, the client code connects the m_exception component to 
   the logfile manage by m_logger. This way, the exception messages are collected in the 
   unique log file of the client code.</p>
<pre class="example">
     call log_startup ( &quot;log_file.log&quot; , append=.true. )
     call log_cget ( &quot;logfileunit&quot; , log_fileunit )
     call exception_setstoponerror ( .false. )
     call exception_setlogunit ( log_fileunit )
     call exception_raiseError ( &quot;This message will be written in log_file.log and the execution will continue.&quot; )
     call log_shutdown ()
</pre>
</div>
<div id="subsection4" class="subsection"><h3><a name="subsection4">Pseudo-catch</a></h3>
<p>The client code can use a pseudo-catch system which provides
a simple way to manage exceptions which are raised at a lower
level in the call stack. This allows to provide special
treatments when exceptions are generated, without modifiying
all lower level subroutines/function, but just by inserting
exception management when needed.
Suppose that you have a subroutine which source code is the following.</p>
<pre class="example">
     subroutine yoursubroutine ()
       use m_exception, only : exception_raiseFatalError
       implicit none
       [...]
       call exception_raiseFatalError ( &quot;Wrong blabla in yoursubroutine&quot; )
       [...]
     end subroutine yoursubroutine
</pre>
<p>When calling the subroutine &quot;yoursubroutine&quot;, one may wonder if exceptions
   have been generated so that these errors may be processed, or not.
   One can use the &quot;exception_catch&quot; service to compute the status 
   of one subroutine and manage that status.</p>
<pre class="example">
     use m_exception, only : exception_catch, &amp;
         EXCEPTION_INFORMATION, &amp;
         EXCEPTION_WARNING &amp;
         EXCEPTION_ERROR &amp;
         EXCEPTION_FATAL_ERROR &amp;
         EXCEPTION_FAILURE
     integer :: status
     call exception_catch ( yoursubroutine , status )
     select case ( status )
     case ( EXCEPTION_INFORMATION )
        write(6,*) &quot;Information&quot;
     case ( EXCEPTION_WARNING )
        write(6,*) &quot;Warning&quot;
     case ( EXCEPTION_ERROR , EXCEPTION_FATAL_ERROR , EXCEPTION_FAILURE )
        write(6,*) &quot;Fatal error&quot;
     case default
        write(6,*) &quot;No problem, continue.&quot;
     end select
</pre>
</div>
</div>
<div id="section3" class="section"><h2><a name="section3">ROUTINES</a></h2>
<dl class="definitions">
<dt><a name="1"><b class="method">exception_raiseFatalError</b> ( <i class="arg">message</i> )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">character(len=*), intent(in) ::</b> <i class="arg">message</i></dt>
<dd></dd>
</dl>
<p>Generates a fatal error message and stops the execution.</p></dd>
<dt><a name="2"><b class="method">exception_raiseError</b> ( <i class="arg">message</i> )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">character(len=*), intent(in) ::</b> <i class="arg">message</i></dt>
<dd></dd>
</dl>
<p>Generates an error message and stops the execution.</p></dd>
<dt><a name="3"><b class="method">exception_raiseWarning</b> ( <i class="arg">message</i> )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">character(len=*), intent(in) ::</b> <i class="arg">message</i></dt>
<dd></dd>
</dl>
<p>Generates a warning message.</p></dd>
<dt><a name="4"><b class="method">exception_raiseInformation</b> ( <i class="arg">message</i> )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">character(len=*), intent(in) ::</b> <i class="arg">message</i></dt>
<dd></dd>
</dl>
<p>Generates an information message.</p></dd>
<dt><a name="5"><b class="method">exception_raiseFailure</b> ( <i class="arg">message</i> )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">character(len=*), intent(in) ::</b> <i class="arg">message</i></dt>
<dd></dd>
</dl>
<p>Generates a failure message and stops the execution</p></dd>
<dt><a name="6"><b class="method">exception_setstoponerror</b> ( <i class="arg">stoponerror</i> )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">logical, intent(in) ::</b> <i class="arg">message</i></dt>
<dd></dd>
</dl>
<p>If <i class="arg">stoponerror</i> is true, then when an error, a fatal_error or a failure
is generated, then stop the execution.
If <i class="arg">stoponerror</i> is false, then the same exceptions do not stop the
execution.</p></dd>
<dt><a name="7"><b class="method">exception_initcounter</b> ( )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">logical, intent(in) ::</b> <i class="arg">message</i></dt>
<dd></dd>
</dl>
<p>Reset to 0 all the exceptions counters.</p></dd>
<dt><a name="8"><b class="method">exception_getcounter</b> ( )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">integer, dimension(1:EXCEPTION_SIZE), intent(out) ::</b> <i class="arg">counter</i></dt>
<dd></dd>
</dl>
<p>Returns an array of size EXCEPTION_SIZE indicating the number
of exceptions of each type. The value of <i class="arg">excepcounters ( iexcept )</i>
is the total number of exceptions of type #iexcept generated since the begining 
of the execution. The possible values for iexcept are the following.</p>
<ul class="itemized">
<li><p>counter ( EXCEPTION_INFORMATION ) : total number of information exceptions raised</p></li>
<li><p>counter ( EXCEPTION_WARNING ) : total number of warning exceptions raised</p></li>
<li><p>counter ( EXCEPTION_ERROR ) : total number of error exceptions raised</p></li>
<li><p>counter ( EXCEPTION_FATAL_ERROR ) : total number of fatal error exceptions raised</p></li>
<li><p>counter ( EXCEPTION_FAILURE ) : total number of failure exceptions raised</p></li>
</ul></dd>
<dt><a name="9"><b class="method">exception_report</b> ( )</a></dt>
<dd><p>Writes on the current exception unit number a report
which details the number of exceptions of all types
since the begining of the execution or the last reset of
all counters.</p></dd>
<dt><a name="10"><b class="method">exception_setlogunit</b> ( <i class="arg">unitnumber</i> )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">integer, intent(in) ::</b> <i class="arg">unitnumber</i></dt>
<dd></dd>
</dl>
<p>Set the unit number onto which the messages are output.
If the unitnumber is 0, the messages are written
to the standard output (unit *).</p></dd>
<dt><a name="11"><b class="method">exception_getlogunit</b> ( ) result ( logunit )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">integer ::</b> <i class="arg">logunit</i></dt>
<dd></dd>
</dl>
<p>Returns the unit number onto which the messages are output,
if enabled or 0 if the feature is disabled.</p></dd>
<dt><a name="12"><b class="method">exception_logactive</b> ( <i class="arg">bool</i> )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">logical, intent(in) ::</b> <i class="arg">bool</i></dt>
<dd></dd>
</dl>
<p>If the boolean argument <i class="arg">bool</i> is true, enable the logging 
of the exceptions messages.
If the boolean argument <i class="arg">bool</i> is false, disable the logging
of the exceptions messages.</p></dd>
<dt><a name="13"><b class="method">exception_islogactive</b> ( ) result ( islogactive )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">logical ::</b> <i class="arg">islogactive</i></dt>
<dd></dd>
</dl>
<p>Returns .true. if the current exception messages are written,
either on standard output or into a log file.</p></dd>
<dt><a name="14"><b class="method">exception_catch</b> ( <i class="arg">callback</i> <i class="arg">, status</i> ) result ( islogactive )</a></dt>
<dd><dl class="arguments">
<dt><b class="type">integer, intent(out) ::</b> <i class="arg">status</i></dt>
<dd></dd>
</dl>
<pre class="example">
    interface interfacecallback
       subroutine callback ()
       end subroutine callback
    end interface interfacecallback
</pre>
<p>Calls the given subroutine <i class="arg">callback</i> and set <i class="arg">status</i> as an 
the integer associated with last exception, higher level, code or 0 if no exception
was raised.
Caution : the internal algorithm is based on the exception counters,
which implies that any call to exception_initcounter in the client
code can result in a wrong status.</p></dd>
</dl>
</div>
<div id="section4" class="section"><h2><a name="section4">TODO</a></h2>
<ul class="itemized">
<li><p>design a more powerful exception management system, which manages exceptions
through the call stack.</p></li>
</ul>
</div>
<div id="copyright" class="section"><h2><a name="copyright">Copyright</a></h2>
<p>Copyright &copy; 2008 Michael Baudin michael.baudin@gmail.com<br>
Copyright &copy; 2008 Arjen Markus arjenmarkus@sourceforge.net</p>
</div>
</div></body></html>